import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/Components/Providers";
import Footer from "@/Components/Footer";
import NavbarClient from "@/Components/NavbarClient"; 
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
           {/* <div className="max-w-7xl mx-auto px-4"> */}
            <NavbarClient />
            {children}
             <Toaster position="top-right" reverseOrder={false} />
            <Footer />
          {/* </div> */}
        </Providers>
      </body>
    </html>
  );
}
